### ISSUE TITLE
Eu, como usuário, desejo efetuar meu cadastro

### ISSUE THREAD

**Issue by sumitani** [DellGarcia/API-CSharp#1]
Este ticket tem como objetivo criar uma API que permita o usuário fazer seu cadastro no sistema.

Especificação
A entidade deve conter os seguintes campos: id (string), firstName (string), surname (string), age (int), creationDate (DateTime).

Todos os campos são obrigatórios, exceto o campo surname.

O campo id não deve ser inserido pelo usuário, mas gerado pelo sistema.

O campo creationDate não deve ser inserido pelo usuário, mas preenchido pelo sistema.

Requisitos técnicos
Aplicação deve ser desenvolvida em ASP.NET Core MVC;

Dados devem ser persistidos para um banco de dados utilizando Entity Framework (EF Core);

Aplicação e banco de dados devem rodar dentro de contêineres Docker com imagem Linux (utilizar docker-compose para subir o ambiente).

Registra as operações (criação, deleção, edição etc) em log

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0

Testes unitários

https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test

Requisitos técnicos:
Consultar usuários

GET /Users

Resposta:

[
{ name: 'Cliente 1', surname: 'Sobrenome', age: 25, creationDate: '2020-12-01T01:00:00, id: 'b4f5a-b4f5a-b4f5a-b4f5a-b4f5a' ' },
{ name: 'Cliente 2', surname: 'Sobrenome 2', age: 25, creationDate: '2020-12-01T01:00:00, id: 'b4f5a-b4f5a-b4f5a-b4f5a-b4f5a' ' },
{ name: 'Cliente 3', surname: 'Sobrenome 3', age: 25, creationDate: '2020-12-01T01:00:00, id: 'b4f5a-b4f5a-b4f5a-b4f5a-b4f5a' ' }
]

PUT /Users/{id}

Request:

{
name: 'Novo nome',
surname: 'novo sobrenome',
age: 26
}

DELETE /Users/{id}

POST /Users

Request:

{
name: 'Nome',
surname : 'sobrenome',
age: 25
}

**Comment by DellGarcia** [comment]
Ontem iniciei meus estudos em ASP NET Core, criei minha primeira API usando essa tecnologia.
Além disso instalei o Docker para começar os estudos nele também.

**Comment by sumitani** [comment]
Links de lab e minicurso (mão na massa) sobre docker:
https://labs.play-with-docker.com/
https://www.katacoda.com/courses/docker

**Comment by DellGarcia** [comment]
Consegui realizar a integração da API em ASP Net Core com o banco MySql.
Criei e executei as migrations.
Fora isso resolvi um problema no qual não conseguia realizar a comunicação entre os containers da API e o banco no Docker, era apenas algumas configurações que tive que arrumar!

**Comment by sumitani** [comment]
@DellGarcia
Lembrando, para fazer o mock de alguns objetos dentro de testes unitários é possível utilizar o moq (https://github.com/moq/moq4). 
Quando finalizar a parte de testes unitários verifique a parte de log em arquivo utilizando serilog (oferece suporte a logs estruturados) ou log4net.

**Comment by DellGarcia** [comment]
@sumitani 
Acabei de colocar aqui no repositório as ultimas alterações que fiz no projeto.
Consegui usar a biblioteca do Serilog para gerar os Logs no console e em arquivos!

**Comment by sumitani** [comment]
@DellGarcia no geral bom. Gostei do jeito que resolveu a criação da data 👍 . :)
Como comentado na daily:
- Verificar se o que desenvolveu até agora atende o que está descrito na issue.

Itens verificados pendentes:
- Finalizar logs em arquivo
- Testes unitários

Extras:
- Logs de cenários de erro
- Aplicar níveis de log

**Comment by DellGarcia** [comment]
@sumitani Acabei de fazer o upload dos testes aqui no Github, eu ainda estou pensando em mais alguns testes pra fazer no PUT, mas decidi enviar aqui logo pra você conseguir dar uma olhadinha, pra ver tbm se não tem nada estranho rs.

Qualquer coisa só me marcar aqui!
