### ISSUE TITLE
Eu, como usuário do Mobile, desejo efetuar meu cadastro

### ISSUE THREAD

**Issue by sumitani** [DellGarcia/API-CSharp#2]
**Escopo**
Expor o CRUD de usuários via Api REST.

Criar um aplicativo Mobile que permita ao usuário se cadastrar.

**Requisitos técnicos**
Aplicação deve ser desenvolvida em Xamarin.Forms;

API deve ser feita na aplicação já existente;

Testes unitários;

**Comment by DellGarcia** [comment]
Já adicionei o projeto do app em Xamarin aqui no repositório!

**Comment by DellGarcia** [comment]
As telas com operações de CRUD já estão funcionando, sendo possível realizar a navegação!
Agora estou focando nos testes unitários.

**Comment by sumitani** [comment]
@DellGarcia Como conversado na call, depois do testes unitários, validar como esta a navegação (o que acontece quando clica no botão de voltar).

Extras, gerador de cores de paletas, fazer aquele banho de loja:
https://colors.muz.li/ 

No exemplo do livro do xamarin a validação muda a cor e insere um texto. 
https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/enterprise-application-patterns/

Além do link acima achei este vídeo sobre testes (de forma geral) de Xamarin:
https://www.youtube.com/watch?v=HOfmteIoSV4
