### ISSUE TITLE
Eu, como analista de dados, quero os dados do sistema de jogo importados para o sistema.

### ISSUE THREAD

**Issue by sumitani** [DellGarcia/API-CSharp#3]
Para realizar a importação do ponto de origem, considere as entidades:
Origem:
```
CREATE TABLE JOGO (
ID NUMBER(20,0),
NOME NVARCHAR2(255),
ANO NUMBER(20,0),
ID_GENERO NUMBER(20,0)
)

CREATE TABLE GENERO (
ID NUMBER(20,0)
NOME NVARCHAR2(255),
DESCRICAO NVARCHAR2(500)
)

CREATE TABLE BIBLIOTECA (
ID NUMBER(20,0),
DATA_AQUISICAO TIMESTAMP(4),
ID_USUARIO NUMBER(20,0),
ID_JOGO NUMBER(20,0),
ID_GENERO NUMBER(20,0),
)

CREATE TABLE USUARIO (
ID NUMBER(20,0),
NOME NVARCHAR2(255),
DATA_NASC TIMESTAMP(4)
ID_ENDERECO NUMBER(20,0)
)

CREATE TABLE ENDERECO (
ID NUMBER(20,0),
ENDERECO NVARCHAR2(255),
COMPLEMENTO NVARCHAR2(255),
CIDADE NVARCHAR2(255),
ESTADO NVARCHAR2(255)
)
```
Destino:
USER
- name
- birthday
- address
- complement
- city
- state

LIBRARY
- user
- name
- genre
- year
- acquisition_date

O objetivo deste ticket é:
- Utilizar .net 5, aplicação console (criar novo projeto).
- Criar os dados fake do ponto de origem para os testes de integração.
- Criar uma aplicação que faça a leitura destes dados do ponto de origem ao ponto de destino.
- Criar as duas entidades do sistema de destino.
- Se aplicável a arquitetura, criar testes unitários. Se não houver teste unitário, fazer pelo menos um teste integrado no xUnit.

Tópicos relacionados, palavras-chave:
- ETL
- Desnormalização de dados

**Comment by sumitani** [comment]
@DellGarcia 
O ponto de origem é o banco de dados do cliente. A gente cria um banco e insere dados mockados para testes locais. Partimos da premissa que se a coleta de dados funciona localmente, já é meio caminho andado antes de fazer os testes integrados com o ponto de origem real. No nosso caso só existirá o que você for montar. O motivo é por conta da disponibilidade, caso mudarem a politica de segurança dos dados, como faremos o desenvolvimento e testes das funcionalidades?

O ponto de destino é um segundo banco de dados do _seu_ sistema.

O sistema é para que o analista consiga extrair as consultas necessárias para os clientes.

A ideia é você fazer um tratamento de ETL em C#. As bibliotecas podem auxiliar nas conexões e na leitura assim como você tinha utilizado aquela biblioteca para MySQL. 
Quiser utilizar alguma biblioteca pronta, me avise a gente verifica se pode ser utilizado.

**Comment by DellGarcia** [comment]
Acabei de fazer upload da versão mais recente do projeto, dei uma revisada nos itens do ticket e acho que já está tudo de acordo com os requisitos, aí na Daily te mostro pra ver se tá tudo OK!

**Comment by sumitani** [comment]
Item finalizado. :) Verificar o projeto ETL.Project.
